### ISSUE TITLE
'Other' radio text input required

### ISSUE THREAD

**Issue by gyrus** [ovann86/gravity-forms-wcag-20-form-fields#3]
I think there may be an issue here. Is the 'Other' text input being marked as 'required' (HTML and ARIA) simply if the radio group is required. Might this need some JS to make the text field required only if the 'Other' radio option is selected?

**Comment by ovann86** [comment]
Hi gyrus,

I think the solution to this is to NOT apply the required attribute(s) to the radio inputs, but to the fieldset.

I couldn't find anything conclusing in the spec HTML or aria specs, so I'll reference this (option 1):

http://stackoverflow.com/questions/8509481/aria-required-in-a-radio-group= 1.2.8  

I'll impement this in version 1.2.9.

Thanks for raising this issue and please let me know if you disagree with taking this approach.

Will also let you know once I update GitHub with the latest code.

**Comment by gyrus** [comment]
Don't have time til later today to look at this, but I see the updates out already! Will have a look later. Thanks for the attention to this.

**Comment by gyrus** [comment]
Adding the attribute to the fieldset makes sense I think. Again, thanks for having a look at this.
