### ISSUE TITLE
Error on Forms Page

### ISSUE THREAD

**Issue by mrwweb** [ovann86/gravity-forms-wcag-20-form-fields#5]
I'm seeing the following error in the footer of a page using this plugin:

> Strict Standards: call_user_func_array() expects parameter 1 to be a valid callback, non-static method ITSP_GF_WCAG20_Form_Fields::queue_scripts_js_script() should not be called statically in /path/to/site/wp-includes/plugin.php on line 496

**Comment by ovann86** [comment]
Hey,

Thanks for pointing this out.

I fixed this awhile ago, but havent updated the repo on github.

Sorry for not replying sooner, I keep forgetting my github password and it locks me out after too many attempts!

I'll update github now that im logged in.
